### ISSUE TITLE
TypeError issue in mesh library

### ISSUE THREAD

**Issue by minyoung-mia-Kim** [pixelite1201/pytorch_coma#1]
Hi, 

I've tried to test CoMA source code(pytorch version) and I nearly got this, but finally met a library issue I couldn't find any solution.

The error is...
TypeError: argument 1 must be numpy.ndarray, not numpy.ndarray

I've got this while running below and when I run the test code the library seems not to be able to load meshes properly.

run main.py --data_dir /data --checkpoint_dir /checkpoints (this is from CoMA code)

/opt/conda/envs/py355/lib/python3.5/site-packages/psbody/mesh/mesh.py in compute_aabb_tree(self)
    438 
    439     def compute_aabb_tree(self):
--> 440         return search.AabbTree(self)
    441 
    442     def compute_aabb_normals_tree(self):

/opt/conda/envs/py355/lib/python3.5/site-packages/psbody/mesh/search.py in __init__(self, m)
     22         from . import spatialsearch
     23         # this shit return NULL
---> 24         self.cpp_handle = spatialsearch.aabbtree_compute(m.v.astype(np.float64).copy(order='C'), m.f.astype(np.uint32).copy(order='C'))
     25 
     26     def nearest(self, v_samples, nearest_part=False):

**TypeError: argument 1 must be numpy.ndarray, not numpy.ndarray**

If you got through this problem, please give me some help.
Or can I ask you checkpoint file of this pytorch model?

I also opened this issue in https://github.com/MPI-IS/mesh/issues/24#issue-537022177 too.

Thank you in advanced

**Comment by pixelite1201** [comment]
Please refer to [MPI-IS/mesh](https://github.com/MPI-IS/mesh/issues/24#issue-537022177)
