### ISSUE TITLE
RuntimeError: The size of tensor a (29990) must match the size of tensor b (5023) at non-singleton dimension 0

### ISSUE THREAD

**Issue by redredbluee** [pixelite1201/pytorch_coma#3]
Hi，I try to use this code to train the coma data,but I met this error:

Traceback (most recent call last):
  File "/home/xx/code/cccoma/pytorch_coma-master/main.py", line 208, in <module>
    main(args)
  File "/home/xx/code/cccoma/pytorch_coma-master/main.py", line 135, in main
    train_loss = train(coma, train_loader, len(dataset), optimizer, device)
  File "/home/xx/code/cccoma/pytorch_coma-master/main.py", line 159, in train
    out = coma(data)  
  File "/home/xx/anaconda3/envs/mesh/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xx/code/cccoma/pytorch_coma-master/model.py", line 34, in forward
    x = self.encoder(x)
  File "/home/xx/code/cccoma/pytorch_coma-master/model.py", line 41, in encoder
    x = F.relu(self.cheb[i](x, self.A_edge_index[i], self.A_norm[i]))
  File "/home/xx/anaconda3/envs/mesh/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xx/code/cccoma/pytorch_coma-master/layers.py", line 41, in forward
    Tx_1 = self.propagate(edge_index, x=x, norm=norm)
  File "/home/xx/anaconda3/envs/mesh/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 236, in propagate
    out = self.message(**msg_kwargs)
  File "/home/xx/code/cccoma/pytorch_coma-master/layers.py", line 57, in message
    return norm.view(-1, 1, 1) * x_j
RuntimeError: The size of tensor a (29990) must match the size of tensor b (5023) at non-singleton dimension 0
/opt/conda/conda-bld/pytorch_1595629416375/work/aten/src/THC/THCTensorIndex.cu:272: indexSelectLargeIndex: block: [27,0,0], thread: [96,0,0] Assertion `srcIndex < srcSelectDimSize` failed

And I show the data size of line41  in layer.py. They are(edge_index, x=x, norm=norm):
 torch.Size([2, 29990]) torch.Size([5023, 16, 3]) torch.Size([29990])
how can I solve this error? looking forward to your help.

**Comment by four-happy-meatball** [comment]
Hi, when I run the coma code, I have also met the problem like you. when I run the code "return norm.view(-1, 1, 1) * x_j"
"The size of tensor a (29990) must match the size of tensor b (5023) at non-singleton dimension 0"
Do you find the solution?
if yes,could you tell me how to do this.Many thanks

**Comment by JacopoBartoli** [comment]
Hi, I had the same issues and I solved this particular problem.Inside the ChebConv_Coma class constructor I setted the attribute self.node_dim to 0 (it was -2 instead). This solved that problem, but inside the Pool layer a similar issue occurs. Do you have any advice?
I updated some Tensor dimension and succeded in running the training and the tests but, probably for some errors within my code, the graphical results are much worst than the results showed in the original paper.

**Comment by pixelite1201** [comment]
Can you tell me what is the shape of norm and  x_j in line 57 of layers.py?
return norm.view(-1, 1, 1) * x_j

**Comment by redredbluee** [comment]
> Can you tell me what is the shape of norm and x_j in line 57 of layers.py?
> return norm.view(-1, 1, 1) * x_j

the size of  x_j is [5023, 29990,3]
the size of  norm.view(-1, 1, 1) is [29990, 1, 1]

**Comment by pixelite1201** [comment]
Thanks. I see in your previous comment that you put node_dim to 0. Can you also post the trace log for a run without any changes to the code?

**Comment by pixelite1201** [comment]
After going through the code, it seems like there is torch_geometric version mismatch. Can you do pip freeze > requirements.txt in your repo and provide me the file. I will try to replicate the issue on my side.

**Comment by redredbluee** [comment]
> After going through the code, it seems like there is torch_geometric version mismatch. Can you do pip freeze > requirements.txt in your repo and provide me the file. I will try to replicate the issue on my side.

[requirements.txt](https://github.com/pixelite1201/pytorch_coma/files/6049675/requirements.txt)

**Comment by redredbluee** [comment]
> Hi, I had the same issues and I solved this particular problem.Inside the ChebConv_Coma class constructor I setted the attribute self.node_dim to 0 (it was -2 instead). This solved that problem, but inside the Pool layer a similar issue occurs. Do you have any advice?
> I updated some Tensor dimension and succeded in running the training and the tests but, probably for some errors within my code, the graphical results are much worst than the results showed in the original paper.

I am sorry to say that i have not solved the problem.
The mean euclidean error is 0.845 ± 0.994mm in the original paper. I was wandering what is your results (like train loss, val loss, val euclidean ) , and how many face meshes  you used for the training dataset.

**Comment by pixelite1201** [comment]
> > After going through the code, it seems like there is torch_geometric version mismatch. Can you do pip freeze > requirements.txt in your repo and provide me the file. I will try to replicate the issue on my side.
> 
> [requirements.txt](https://github.com/pixelite1201/pytorch_coma/files/6049675/requirements.txt)
With the provided requirements.txt file, I face the same issue as JacopoBartoli.
I updated the requirements.txt file in the repo with the supported version. Can you try to reinstall this in a new environment and try again?

**Comment by redredbluee** [comment]
> > > After going through the code, it seems like there is torch_geometric version mismatch. Can you do pip freeze > requirements.txt in your repo and provide me the file. I will try to replicate the issue on my side.
> > 
> > 
> > [requirements.txt](https://github.com/pixelite1201/pytorch_coma/files/6049675/requirements.txt)
> > With the provided requirements.txt file, I face the same issue as JacopoBartoli.
> > I updated the requirements.txt file in the repo with the supported version. Can you try to reinstall this in a new environment and try again?
Hi, I reinstalled a new env with your requirements.txt(torch-geometric==1.3.2).  But I found a new error during the process of loading obj data, which is not occured in the old env(torch-geometric=1.6.1). I runed the origin code. did you met this error?
`Traceback (most recent call last):
  File "/home/xx/code/pytorch_coma-master/main.py", line 219, in <module>
    main(args)
  File "/home/xx/code/pytorch_coma-master/main.py", line 107, in main
    dataset = ComaDataset(data_dir, dtype='train', split=args.split, split_term=args.split_term, pre_transform=normalize_transform)
  File "/home/xx/code/pytorch_coma-master/data.py", line 22, in __init__
    super(ComaDataset, self).__init__(root_dir, transform, pre_transform)
  File "/home/xx/anaconda3/envs/ccoma/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 52, in __init__
    pre_filter)
  File "/home/xx/anaconda3/envs/ccoma/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 103, in __init__
    self._download()
  File "/home/xx/anaconda3/envs/ccoma/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 139, in _download
    self.download()
  File "/home/xx/anaconda3/envs/ccoma/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 43, in download
    raise NotImplementedError
NotImplementedError
`

**Comment by JacopoBartoli** [comment]
[requirements.txt](https://github.com/pixelite1201/pytorch_coma/files/6175230/requirements.txt)

This is my results of the pip freeze command, I don't know if it can help. The graphical results that I obtained are aligned to the paper's ones.
Regarding the losses during the test phase, using a random split of test and training set, i obtained: L1=0.1758, Euclidean=0.9499.

**Comment by UchihaBarry** [comment]
> [requirements.txt](https://github.com/pixelite1201/pytorch_coma/files/6175230/requirements.txt)
> 
> This is my results of the pip freeze command, I don't know if it can help. The graphical results that I obtained are aligned to the paper's ones. Regarding the losses during the test phase, using a random split of test and training set, i obtained: L1=0.1758, Euclidean=0.9499.

i've setted the attribute self.node_dim to 0 and the pool layer got error,can u tell me what to do then?

**Comment by Alex-bd** [comment]
> Hi, I had the same issues and I solved this particular problem.Inside the ChebConv_Coma class constructor I setted the attribute self.node_dim to 0 (it was -2 instead). This solved that problem, but inside the Pool layer a similar issue occurs. Do you have any advice? I updated some Tensor dimension and succeded in running the training and the tests but, probably for some errors within my code, the graphical results are much worst than the results showed in the original paper.

May I ask how you resolved similar issues with the pool layer? The error message is: ValueError: Encountered tense with size 16 in dimension -2, but expected size 1256

**Comment by Alex-bd** [comment]
> > [requirements.txt](https://github.com/pixelite1201/pytorch_coma/files/6175230/requirements.txt)
> > This is my results of the pip freeze command, I don't know if it can help. The graphical results that I obtained are aligned to the paper's ones. Regarding the losses during the test phase, using a random split of test and training set, i obtained: L1=0.1758, Euclidean=0.9499.
> 
> i've setted the attribute self.node_dim to 0 and the pool layer got error,can u tell me what to do then?

I have encountered the same problem as you. Have you resolved it?
