### ISSUE TITLE
Can you provide the trained model for fast testing?

### ISSUE THREAD

**Issue by konatasick** [pixelite1201/pytorch_coma#9]
Is there any pre-trained model or colab notebook for fast testing?

**Comment by pixelite1201** [comment]
You can get the trained model from project website https://coma.is.tue.mpg.de/

**Comment by konatasick** [comment]
> You can get the trained model from project website https://coma.is.tue.mpg.de/

I cannot find the trained model in the website. The tf1 model can be found in https://github.com/anuragranj/coma . I want to download pytorch trained model used in your codes.

**Comment by liaoksn** [comment]
> 
@
Have you finally got a pretrained model in pytorch version ? I'm facing the same question

> > You can get the trained model from project website https://coma.is.tue.mpg.de/
> 
> I cannot find the trained model in the website. The tf1 model can be found in https://github.com/anuragranj/coma . I want to download pytorch trained model used in your codes.
